# Generated by Django 4.1.1 on 2022-09-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='timecreated',
        ),
    ]
