# Generated by Django 4.1.1 on 2022-09-10 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_timecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisit',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
