# Generated by Django 4.1.1 on 2022-09-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlisit',
            new_name='watchlist',
        ),
    ]
